services:
  java-app:
    build:
      context: .
    container_name: java-app
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"  # Exposed by Dockerfile (Spring Boot default)
    # env_file: ./.env  # Uncomment if .env file exists
    # Add depends_on here if you add external services below
    networks:
      - appnet

# No external services (databases, caches, etc.) detected in project structure or Dockerfile.
# If your application requires a database or other service, add it below.

networks:
  appnet:
    driver: bridge
